# Generated by Django 4.2 on 2023-04-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id_comment', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250)),
                ('main_comment_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id_device', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('premier', models.DateField()),
                ('device_type', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('picture', models.BinaryField(null=True)),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id_os', models.IntegerField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('theme', models.BooleanField()),
                ('admin_acc', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id_spec', models.IntegerField(primary_key=True, serialize=False)),
                ('processor', models.CharField(max_length=50, null=True)),
                ('ram', models.IntegerField(null=True)),
                ('memory', models.IntegerField(null=True)),
                ('battery', models.IntegerField(null=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('price', models.FloatField(null=True)),
                ('screen_type', models.CharField(max_length=20, null=True)),
                ('devices_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
            ],
        ),
        migrations.CreateModel(
            name='OS_devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
                ('os_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.os')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField()),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.comment')),
                ('devices_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
                ('os_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.os')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Followed_devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Error_report',
            fields=[
                ('id_error', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(null=True)),
                ('devices_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
                ('os_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.os')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='devices_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.devices'),
        ),
        migrations.AddField(
            model_name='comment',
            name='os_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.os'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
