# Generated by Django 4.2 on 2023-04-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='os',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='os',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='os',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
