# Generated by Django 4.2 on 2023-04-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_devices_name_alter_os_version_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_acc',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.BooleanField(default=0),
        ),
    ]
