# Generated by Django 4.2 on 2023-04-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_admin_acc_alter_user_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='sieama', max_length=50, unique=True),
        ),
    ]
