# Generated by Django 4.2 on 2023-04-18 11:16

from django.db import migrations, models
import main.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_login_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
